baseurl: '/'
domain: skratsch-solutions.github.io
url: https://skratsch-solutions.github.io
permalink: pretty
title: 'Jekyll Serif'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home:
  limit_services: 6

collections:
  it-services:
    output: true
    sort_by: weight
  software-services:
    output: true
    sort_by: weight
  posts:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "it-services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "software-services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
